from typing import Optional

class _Warnings:
    @staticmethod
    def auth_with_anon_weaviate() -> None: ...
    @staticmethod
    def auth_no_refresh_token(auth_len: Optional[int] = ...) -> None: ...
    @staticmethod
    def auth_negative_expiration_time(expires_in: int) -> None: ...
    @staticmethod
    def auth_header_and_auth_secret() -> None: ...
    @staticmethod
    def auth_cannot_parse_oidc_config(url: str) -> None: ...
    @staticmethod
    def weaviate_server_older_than_1_14(server_version: str) -> None: ...
    @staticmethod
    def manual_batching() -> None: ...
    @staticmethod
    def weaviate_too_old_for_openai(server_version: str) -> None: ...
    @staticmethod
    def token_refresh_failed(exc: Exception) -> None: ...
    @staticmethod
    def weaviate_too_old_vs_latest(server_version: str) -> None: ...
    @staticmethod
    def weaviate_client_too_old_vs_latest(client_version: str, latest_version: str) -> None: ...
    @staticmethod
    def use_of_client_batch_will_be_removed_in_next_major_release() -> None: ...
