from .classification import Classification as Classification
from weaviate.connect import Connection as Connection
from weaviate.exceptions import UnexpectedStatusCodeException as UnexpectedStatusCodeException

class ConfigBuilder:
    def __init__(self, connection: Connection, classification: Classification) -> None: ...
    def with_type(self, classification_type: str) -> ConfigBuilder: ...
    def with_k(self, k: int) -> ConfigBuilder: ...
    def with_class_name(self, class_name: str) -> ConfigBuilder: ...
    def with_classify_properties(self, classify_properties: list) -> ConfigBuilder: ...
    def with_based_on_properties(self, based_on_properties: list) -> ConfigBuilder: ...
    def with_source_where_filter(self, where_filter: dict) -> ConfigBuilder: ...
    def with_training_set_where_filter(self, where_filter: dict) -> ConfigBuilder: ...
    def with_target_where_filter(self, where_filter: dict) -> ConfigBuilder: ...
    def with_wait_for_completion(self) -> ConfigBuilder: ...
    def with_settings(self, settings: dict) -> ConfigBuilder: ...
    def do(self) -> dict: ...
