from weaviate.connect import Connection as Connection
from weaviate.exceptions import UnexpectedStatusCodeException as UnexpectedStatusCodeException

class Contextionary:
    def __init__(self, connection: Connection) -> None: ...
    def extend(self, concept: str, definition: str, weight: float = ...) -> None: ...
    def get_concept_vector(self, concept: str) -> dict: ...
